// User prompt pools and domain list for Dataset Generator V2

export const USER_PROMPTS_INITIAL: string[] = [
  "I need you to perform a full reconnaissance on {domain}. Start with subdomain enumeration and identify the tech stack.",
  "Begin an external assessment of {domain}. Map the full attack surface — subdomains, open ports, exposed services, API endpoints.",
  "Run passive and active recon on {domain}. I need a complete picture of what's exposed.",
  "Start the engagement against {domain}. Phase 1: recon. Find everything you can without being too noisy.",
  "Map the attack surface of {domain}. I want subdomains, live hosts, technologies, and any quick wins.",
  "I'm starting a pentest on {domain}. Do the initial recon phase — subdomain enum, port scanning, tech fingerprinting.",
  "Assess the external exposure of {domain}. Focus on finding entry points for web app testing.",
  "Begin with comprehensive reconnaissance of {domain}. I need subdomains, directory listings, and technology identification.",
  "Enumerate {domain} thoroughly. Check for exposed services, admin panels, API docs, and any information disclosure.",
  "I have authorization to test {domain}. Start with OSINT and passive recon, then move to active enumeration.",
  "Let's start the assessment of {domain}. First, I need you to discover all subdomains and check which ones are alive.",
  "Scope: {domain}. Do a full external recon. I want to know every subdomain, every open port, every technology they use.",
  "Kick off the web app assessment of {domain}. Start by understanding the architecture and tech stack.",
  "I need a thorough attack surface analysis of {domain} before we start testing. Map everything you can find.",
  "We're authorized to test {domain}. Start with reconnaissance — subdomains, ports, directories, technologies. Be thorough.",
  "Run initial recon against {domain}. I want to identify high-value targets before we start the active testing phase.",
  "The client is {domain}. Begin the penetration test with external reconnaissance. I need a sitemap of their exposure.",
  "Conduct a comprehensive discovery phase against {domain}. Enumerate subdomains, identify live services, and detect technologies.",
  "I'm testing {domain} as part of a bug bounty program. Start with recon — find interesting targets on their infrastructure.",
  "Let's do the recon phase for {domain}. I need to understand their attack surface before choosing where to focus testing.",
];

export const USER_PROMPTS_VULN_TESTING: string[] = [
  "Test the endpoint at {endpoint} for injection vulnerabilities. Try SQL injection, template injection, and command injection.",
  "I found an interesting parameter '{param}' at {endpoint}. Fuzz it and check for common web vulnerabilities.",
  "The {endpoint} endpoint looks like it might be vulnerable. Test it for OWASP Top 10 issues.",
  "Check {endpoint} for broken access control. Can you access other users' data by manipulating IDs?",
  "Run a comprehensive vulnerability scan on {endpoint}. Focus on injection and authentication issues.",
  "I noticed the '{param}' parameter is reflected in the response. Test it for XSS — try different contexts and encodings.",
  "The API at {endpoint} returns more data than the UI shows. Check if it's leaking sensitive information.",
  "Test {endpoint} for authentication bypass. Try JWT manipulation, default credentials, and session handling issues.",
  "Check if the {endpoint} endpoint is vulnerable to SSRF. It seems to fetch external resources.",
  "I want you to test {endpoint} for SQL injection. The '{param}' parameter looks suspicious.",
  "The GraphQL endpoint at {endpoint} might allow introspection. Check for schema exposure and authorization issues.",
  "Test the file upload at {endpoint} for unrestricted upload, path traversal, and content type bypasses.",
  "Check {endpoint} for race conditions. The application doesn't seem to handle concurrent requests properly.",
  "I found a redirect parameter at {endpoint}. Test it for open redirect and see if it can be chained with other issues.",
  "The search functionality at {endpoint} might be injectable. Test the '{param}' parameter thoroughly.",
  "Test {endpoint} for CORS misconfiguration. Check if it reflects arbitrary origins with credentials.",
  "Check the WebSocket at {endpoint} for cross-site hijacking and missing origin validation.",
  "The application at {endpoint} uses client-side rendering. Check for DOM-based XSS and prototype pollution.",
  "Test {endpoint} for HTTP request smuggling. The frontend and backend might disagree on request parsing.",
  "I want to check {endpoint} for business logic flaws. Test negative values, duplicate submissions, and parameter tampering.",
  "Check the JWT implementation at {endpoint}. Test for algorithm confusion, weak secrets, and token manipulation.",
  "The API at {endpoint} uses numeric IDs. Test every endpoint for IDOR — can a regular user access admin data?",
  "Test {endpoint} for SSTI. The application seems to render user input through a template engine.",
  "Check {endpoint} for cache poisoning. The CDN might serve different content based on unkeyed headers.",
  "I noticed the application at {endpoint} has rate limiting. Can you bypass it through race conditions or header manipulation?",
];

export const USER_PROMPTS_EXPLOIT: string[] = [
  "I confirmed {vulnType} at {endpoint}. Exploit it fully and demonstrate the maximum impact.",
  "The {vulnType} vulnerability is confirmed. Show me the worst-case scenario — extract everything you can.",
  "Exploit the {vulnType} finding and try to escalate. Can we get from this to admin access or RCE?",
  "Take the {vulnType} vulnerability further. Chain it with anything else you find for maximum impact.",
  "Demonstrate full exploitation of the {vulnType} issue. I need a solid PoC with evidence for the client.",
  "The target is vulnerable to {vulnType}. Extract sensitive data and show me the full attack chain.",
  "Escalate the {vulnType} finding. What's the worst thing an attacker could do with this vulnerability?",
  "I need a complete exploitation of {vulnType}. Show me data extraction, privilege escalation — the whole chain.",
  "Can you weaponize the {vulnType} finding? I want to demonstrate to the client why this is critical severity.",
  "Take {vulnType} all the way. I want to see full exploitation with evidence of impact.",
  "The {vulnType} is confirmed. Now I need you to demonstrate the real-world impact — data breach, account takeover, whatever's possible.",
  "Exploit the {vulnType} finding and check for post-exploitation opportunities. What can we reach from here?",
  "Show me how an attacker would leverage this {vulnType} vulnerability in a real attack scenario.",
  "The {vulnType} issue gives us an initial foothold. Now try to escalate privileges and move laterally.",
  "Use the {vulnType} vulnerability to demonstrate a complete attack chain from initial access to data exfiltration.",
];

export const USER_PROMPTS_FAILURE_FOLLOWUP: string[] = [
  "That didn't work. Try a different approach — maybe a different encoding or bypass technique.",
  "The WAF blocked that. Can you find a way around the filter?",
  "Hmm, no results. Let's try testing different parameters or a different endpoint.",
  "The standard payload failed. Can you write a custom script to handle this edge case?",
  "That was blocked. Try encoding the payload differently or using a different injection technique.",
  "No luck there. What alternative attack vectors should we try instead?",
  "Interesting — the defense caught that. What does the block response tell us about their security?",
  "That endpoint seems hardened. Let's try the same vulnerability class on a different endpoint.",
  "The automated tool didn't find anything. Can you do manual testing with targeted payloads?",
  "Let's pivot. That attack path is a dead end — what other vulnerabilities should we check?",
  "The parameter seems filtered. Can you bypass the validation? Try double encoding, unicode, or null bytes.",
  "That's being blocked. Write a Python script to test this with custom payloads and timing analysis.",
  "Move on to the next test case. If one vector is blocked, there's usually a weaker point elsewhere.",
  "Try testing the same vulnerability but through the API instead of the web interface.",
  "The direct approach failed. Can you chain this with another finding to achieve the same goal indirectly?",
];

export const USER_PROMPTS_REPORT: string[] = [
  "Write up all findings as a professional pentest report. Include CVSS scores, evidence, and remediation.",
  "Generate a detailed finding report for the {vulnType} vulnerability with reproduction steps and fix recommendations.",
  "Create a comprehensive report. I need executive summary, technical details, and actionable remediation for each finding.",
  "Document all findings professionally. The client needs a report they can hand to their dev team.",
  "Write the vulnerability report. Include severity ratings, attack narratives, evidence screenshots, and compliance impact.",
  "Generate the final report. Focus on business impact — the CISO needs to understand why this matters.",
  "Create a bug bounty report for the {vulnType} finding. Clear PoC, impact assessment, and remediation steps.",
  "Document this finding for the engagement report. I need CVSS vector, CWE reference, and code-level fix recommendations.",
  "Write a professional finding report that explains the attack chain from initial recon through exploitation.",
  "Generate the final deliverable. Executive summary for leadership, technical details for the dev team.",
];

export const USER_PROMPTS_DEEP_ANALYSIS: string[] = [
  "Can you also check for related vulnerabilities in the same area? The codebase might have similar issues.",
  "What's the full blast radius of this vulnerability? How many users could be affected?",
  "Are there any other attack paths we should explore from this finding?",
  "Can you verify this finding with a different technique to make sure it's not a false positive?",
  "How would an attacker maintain persistent access after exploiting this vulnerability?",
  "What compensating controls would you recommend while the development team works on a fix?",
  "Can you test if the WAF would detect this attack in a real scenario?",
  "What would the complete attack chain look like in a real-world targeted attack?",
  "Check if the same vulnerability exists in the mobile API or other application interfaces.",
  "Can you estimate the data exposure scope? How many records are accessible through this vulnerability?",
  "Test if this same issue affects other endpoints or parameters in the application.",
  "How would you detect this attack from the defender's perspective? What logs should the SOC watch?",
  "Can you demonstrate this vulnerability without authentication to assess the unauthenticated attack surface?",
  "What's the regulatory impact of this finding? Does it trigger any mandatory reporting requirements?",
  "How easy would it be for a script kiddie to exploit this versus a sophisticated attacker?",
  "Can you check if this vulnerability is exploitable through the CDN/cache layer as well?",
  "What additional hardening would prevent this entire class of vulnerability, not just this instance?",
  "Test if the same issue exists on the staging or development environments we found during recon.",
  "Can you write a custom exploit script that automates the full attack chain?",
  "How would this vulnerability interact with the cloud infrastructure? Check for privilege escalation to AWS/GCP.",
  "What's the MITRE ATT&CK mapping for this attack chain?",
  "Can you check if the same vulnerable library is used across other microservices?",
  "Test the internal API endpoints we found during SSRF — are they missing authentication?",
];

export const USER_PROMPTS_EVASION: string[] = [
  "The WAF is blocking my payloads. Can you find a way to bypass the filter?",
  "Try encoding the payload differently — double URL encoding, Unicode, or chunked transfer.",
  "The standard approach isn't working. Write a custom script with WAF evasion techniques.",
  "Can you identify the WAF vendor and find known bypass techniques for it?",
  "Try testing through the WebSocket endpoint — it might not have WAF coverage.",
  "Switch to out-of-band techniques since the WAF is blocking inline payloads.",
  "Try the same attack but through a different API version or endpoint.",
  "The rate limiter kicked in. Can you slow down and use more targeted payloads?",
  "Try parameter pollution — send the same parameter twice with different values.",
  "The CDN is caching responses. Can you bypass it to hit the origin directly?",
  "Use timing-based techniques to extract data without triggering the WAF.",
  "Can you find the origin IP behind the CDN? Try DNS history or certificate transparency.",
];

export const DOMAINS = [
  "acme-corp.com", "globex-inc.io", "initech-systems.net", "umbrella-corp.org", "wayne-enterprises.com",
  "stark-industries.com", "oscorp-labs.io", "lexcorp-media.net", "cyberdyne-tech.com", "massive-dynamic.io",
  "pied-piper.dev", "hooli-cloud.net", "soylent-bio.io", "aperture-labs.com", "blackmesa-research.net",
  "weyland-yutani.org", "tyrell-corp.io", "omni-consumer.com", "veridian-dynamics.net", "dundermifflin.co",
  "nexus-financial.com", "zenith-health.io", "atlas-logistics.net", "pinnacle-edu.org", "meridian-energy.com",
  "sentinel-defense.io", "quantum-pharma.net", "frontier-retail.com", "cascade-media.io", "harbor-shipping.net",
  "nova-payments.com", "orbital-cloud.io", "hyperion-saas.net", "vertex-analytics.com", "prism-digital.io",
  "aegis-security.net", "titan-motors.com", "helios-solar.io", "nexgen-telecom.net", "aurora-fintech.com",
  "cobalt-mining.io", "phoenix-healthcare.net", "zenith-aerospace.com", "apex-insurance.io", "stratos-logistics.net",
  "cipher-crypto.com", "vanguard-defense.io", "polaris-navigation.net", "eclipse-media.com", "summit-education.io",
];
