// User prompt pools and protocol list for Smart Contract Security Dataset Generator V2

export const USER_PROMPTS_INITIAL: string[] = [
  "I need a full security audit of the {protocol} protocol. Start with the {contract} contract.",
  "Review {contract}.sol for vulnerabilities. Focus on the {vulnType} attack vector.",
  "I'm running an audit competition on {protocol}. Analyze their {contract} contract.",
  "Begin the security assessment of {protocol}'s {contract} contract. Scope includes all external functions.",
  "We need an independent review of {protocol}. Start with the core contracts and work outward.",
  "Kick off the audit for {protocol}. The {contract} is the highest risk — begin there.",
  "Please audit the {contract} contract in {protocol}. Pay close attention to any {vulnType} patterns.",
  "I've been assigned to review {protocol}. Give me a thorough analysis of {contract} starting with storage layout.",
  "Run a complete security review of {protocol}'s codebase. Priority one is the {contract} contract.",
  "Start the audit engagement for {protocol}. I want you to examine {contract} first and flag any {vulnType} issues.",
  "We're onboarding {protocol} as a client. Begin the smart contract audit with {contract}.",
  "Scope: audit {protocol}. Begin with {contract} and identify all {vulnType} vectors.",
  "I need you to assess {protocol} for security risks. The {contract} contract handles user funds — start there.",
  "New engagement: {protocol}. Do a line-by-line review of {contract} and report findings.",
  "Prepare for the {protocol} audit by reviewing {contract}. I'm particularly worried about {vulnType}.",
  "We have 48 hours to audit {protocol}. Prioritize {contract} and any {vulnType} scenarios.",
  "Client {protocol} submitted their contracts for review. Begin with {contract} and map all entry points.",
  "Start analyzing {protocol}. The {contract} contract is the main risk surface — look for {vulnType} patterns.",
  "I want a comprehensive audit of {protocol}. Begin your deep dive into {contract} and document everything.",
  "Open a new audit workspace for {protocol}. Load {contract} and scan for {vulnType} as your first pass.",
];

export const USER_PROMPTS_VULN_TESTING: string[] = [
  "Check the {function} function in {contract} for {vulnType}.",
  "Can you find {vulnType} in {contract}? The {function} function makes external calls.",
  "Test the {function} calculation for precision loss — amounts get divided before multiplied.",
  "Check if {contract}'s {function} has proper access control. Who can call it?",
  "Run a slither analysis on {contract} and focus on the {function} function for {vulnType}.",
  "Is {vulnType} possible in the {function} flow of {contract}? Trace the full call chain.",
  "Write a test that attempts to trigger {vulnType} through {function} in {contract}.",
  "Audit the {function} function in {contract} — does it properly validate user input against {vulnType}?",
  "The {function} function in {contract} updates state after an external call. Check for {vulnType}.",
  "Fuzz the {function} function in {contract} with extreme values. Could {vulnType} occur?",
  "Map all callers of {function} in {contract}. Are any of them vulnerable to {vulnType}?",
  "Review {contract}.{function} for integer overflow or underflow that could enable {vulnType}.",
  "Does {function} in {contract} correctly handle reentrancy? Test for {vulnType} with a callback contract.",
  "Check if the price feed in {contract}.{function} can be manipulated to cause {vulnType}.",
  "Simulate an attack on {function} in {contract} using a flash loan. Could it lead to {vulnType}?",
  "Verify the rounding direction in {contract}.{function}. Can accumulated rounding errors cause {vulnType}?",
  "Does {function} in {contract} properly check msg.sender? Test for {vulnType} via unauthorized access.",
  "Analyze the token transfer logic in {contract}.{function} for potential {vulnType}.",
  "Can a sandwich attack on {function} in {contract} trigger {vulnType}? Model the MEV scenario.",
  "Check if {contract}.{function} properly handles zero-address inputs. Could that enable {vulnType}?",
];

export const USER_PROMPTS_EXPLOIT: string[] = [
  "I confirmed {vulnType} in {contract}.{function}. Write a Foundry test to prove it.",
  "The {vulnType} vulnerability is confirmed. Create a PoC showing maximum financial impact.",
  "Exploit the {vulnType} finding and try to escalate. What's the worst-case scenario?",
  "Write a fork test on Anvil that demonstrates the full attack chain for {vulnType}.",
  "Build an end-to-end exploit for {vulnType} in {contract}.{function}. Show the exact transaction sequence.",
  "I have a working PoC for {vulnType}. Optimize it to extract the maximum value from {contract}.{function}.",
  "Can you weaponize the {vulnType} in {contract} into a profitable exploit? Show the numbers.",
  "Write a Solidity attack contract that demonstrates {vulnType} against {contract}.{function}.",
  "The {vulnType} in {function} is exploitable. Chain it with an oracle manipulation for maximum damage.",
  "Create a step-by-step Foundry test that reproduces the {vulnType} exploit in {contract}.",
  "Show me the exact calldata needed to trigger {vulnType} on {contract}.{function}.",
  "Build a minimal PoC contract for {vulnType} in {contract}. Keep it under 200 lines.",
  "Can the {vulnType} in {contract}.{function} be combined with a governance attack? Model it.",
  "Write an Anvil fork test that simulates the {vulnType} exploit on mainnet state for {contract}.",
  "The {vulnType} exploit in {contract} needs a setup. Write the test fixtures and the attack in one file.",
];

export const USER_PROMPTS_FAILURE_FOLLOWUP: string[] = [
  "The test reverted. Check if it's a gas limit issue or if the exploit path is blocked.",
  "Slither didn't flag this. Can we write a custom Semgrep rule to catch it?",
  "The fuzz test didn't find anything. Try invariant testing with stateful fuzzing.",
  "That finding was dismissed as a false positive. Let me re-examine the code path.",
  "The PoC is failing on the latest compiler version. Check if a Solidity patch fixed the {vulnType}.",
  "Aderyan ran but returned no findings. Are we looking at a blind spot in the tool or is this contract clean?",
  "The invariant test passed 10,000 runs. Try increasing the sequence depth or adding new invariants.",
  "I got a false alarm on {vulnType}. The require statement in {function} actually prevents it. Confirm and close.",
  "The static analysis tool flagged a medium severity {vulnType} but manual review shows it's unreachable. Verify.",
  "Fuzzing found nothing after 50,000 runs. Maybe the {vulnType} only triggers under specific chain conditions.",
  "The exploit worked on Goerli but fails on mainnet fork. Check for chain-specific state assumptions.",
  "My attack contract runs out of gas before completing the {vulnType} chain. Optimize the calldata.",
  "The symbolic execution engine timed out. Can you manually trace the {function} path for {vulnType}?",
  "CI pipeline failed — the test passes locally but not in the runner. Check the Foundry config.",
  "The vulnerability was patched in the latest commit. Re-run the {vulnType} test against the new {contract}.",
];

export const USER_PROMPTS_REPORT: string[] = [
  "Write the audit finding for this {vulnType} issue. Include severity, description, PoC, and fix.",
  "Generate the full audit report with CVSS score and secure code recommendation.",
  "Document the {vulnType} vulnerability with impact analysis and remediation steps.",
  "Draft the findings section for {vulnType} in {contract}. Include a code snippet of the vulnerable line and the patched version.",
  "Write up the {vulnType} finding for {contract}.{function}. Use the standard format: summary, risk, recommendation.",
  "Produce an audit report entry for {vulnType}. Assign a severity rating and explain your reasoning.",
  "Create the vulnerability report for {vulnType} in {contract}. Include attack scenario and estimated loss.",
  "Write the executive summary for the {vulnType} finding. Make it readable for non-technical stakeholders.",
  "Format the {vulnType} finding according to the Immunefi template. Include steps to reproduce.",
  "Compile the final audit report section for {vulnType} in {contract}.{function}. Add references to similar past incidents.",
];

export const USER_PROMPTS_DEEP_ANALYSIS: string[] = [
  "Do a deeper analysis of the {function} function. Check all external calls and state transitions.",
  "Trace the full execution path from {function} through all internal calls.",
  "Map the complete storage layout of {contract}. Identify any slot collisions or packing issues.",
  "Follow the data flow from user input in {function} to the final state update. Are there any unchecked intermediaries?",
  "Do a comprehensive review of {contract}'s inheritance chain. Are there any shadowing or initialization risks?",
  "Analyze the upgrade pattern in {contract}. Is the proxy initialization safe from {vulnType}?",
  "Cross-reference all events in {contract} with state changes. Are any critical updates missing event emissions?",
  "Deep-dive into the math in {function}. Prove that the formulas are correct under all input ranges.",
  "Examine {contract}'s error handling. Are any revert conditions silently swallowed or misclassified?",
  "Review the role-based access in {contract}. Can a lower-privilege role escalate through {function}?",
];

export const USER_PROMPTS_EVASION: string[] = [
  "The direct {vulnType} path is blocked by {missingCheck}. Is there an indirect attack vector?",
  "Can we bypass the {missingCheck} through a different code path in {contract}?",
  "The require statement prevents the straightforward {vulnType} exploit. Look for a workaround.",
  "The {missingCheck} blocks the primary attack. Can we manipulate state beforehand to neutralize it?",
  "Is there a way to trigger {vulnType} without directly calling {function}? Maybe through a callback or hook?",
  "The {missingCheck} is in place but relies on an oracle. Can we feed it bad data to enable {vulnType}?",
  "The direct path is patched. Check if a previous version of {contract} still has the {vulnType} vulnerability.",
  "Can we use a delegatecall to an untrusted contract to bypass {missingCheck} and achieve {vulnType}?",
  "The {missingCheck} only covers the happy path. What happens on the revert path — can {vulnType} slip through?",
  "Front-running protection is in place, but can a flashbots bundle still execute {vulnType} in {contract}?",
];

export const DOMAINS: string[] = [
  "Alchemix",
  "ZeroLend",
  "Folks Finance",
  "Puffer Finance",
  "Lombard Finance",
  "DeGate",
  "Fuel Network",
  "Celo",
  "BadgerDAO",
  "Aave",
  "Compound",
  "Uniswap",
  "Curve",
  "Lido",
  "Eigenlayer",
  "Saffron",
  "Ostium",
  "Shardeum",
  "Anvil Protocol",
  "Jito",
];
